name: sonicdb
description: SonicDb generator inspired by Room.
version: 0.0.1
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  analyzer: ^1.2.0
  build: ^2.0.0
  built_collection: ^5.0.0
  code_builder: ^3.7.0
  dart_style: ^2.0.0
  source_gen: ^1.0.0
  tuple: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.12.2
  flutter_test_ui: ^1.0.0
  integration_test: ^1.0.2+2
  source_gen_test: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.mixaline.sonicdb
        pluginClass: SonicDbPlugin
