name: sonicdb
description: SonicDb generator inspired by Room database in android.
version: 0.0.2
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  analyzer: ^4.7.0
  build: ^2.0.0
  built_collection: ^5.0.0
  code_builder: ^4.0.0
  dart_style: ^2.0.0
  source_gen: ^1.0.1
  tuple: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4
  flutter_test_ui: ^2.0.0
  integration_test:
    sdk: flutter
  source_gen_test: ^1.0.3

flutter:
  plugin:
    platforms:
      android:
        package: com.mixaline.sonicdb
        pluginClass: SonicDbPlugin
